#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2020.1.11f1"
#define UNITY_VERSION_DIGITS "2020.1.11"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2020
#define UNITY_VERSION_MAJ 1
#define UNITY_VERSION_MIN 11
#define UNITY_IS_BETA 0
